/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Ejecucion.TRABAJOEDAGRUPAL;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import Modelo.Eleccion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CrearEleccion extends javax.swing.JFrame {

    /**
     * Creates new form CrearEleccion
     */
    private DefaultTableModel modelo;    
    private RegistrarEleccion refElecciones;
    String selec;
    JComboBox<String> comboElecciones;
    
    public CrearEleccion() {
        initComponents();
        this.txtId.setText(Integer.toString(TRABAJOEDAGRUPAL.idE));
        modelo = new DefaultTableModel(); 
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Día");
        modelo.addColumn("Mes");
        modelo.addColumn("Año");
        modelo.addColumn("Estado");

        this.TablaElecciones.setModel(modelo);
        String[] opciones = {"", "Presidencial", "Municipal", "Regional"};
        comboElecciones = new JComboBox<>(opciones);

        // Configurar el JComboBox
        comboElecciones.setBounds(70, 160, 170, 30); // Usar AbsoluteConstraints
        comboElecciones.setSelectedIndex(-1); // Inicia vacío
        comboElecciones.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = comboElecciones.getSelectedIndex();
                if (selectedIndex == -1) { // Nada seleccionado aún
                    System.out.println("No has seleccionado ninguna opción.");
                } else {
                    selec = (String) comboElecciones.getSelectedItem();
                    System.out.println("Seleccionaste: " + selec);
                }
            }
        });
        bg.add(comboElecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 170, 30));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaElecciones = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        agregar3 = new javax.swing.JButton();
        txtAño = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(2, 54, 114));
        jLabel15.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 54, 114));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Oficina Nacional de Procesos Electorales");

        jPanel4.setBackground(new java.awt.Color(221, 0, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel16.setBackground(new java.awt.Color(2, 54, 114));
        jLabel16.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 54, 114));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ONPE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel16))
                    .addComponent(jLabel15)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 240, 90));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELECCION");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 60));

        jPanel6.setBackground(new java.awt.Color(2, 54, 114));

        jPanel7.setBackground(new java.awt.Color(221, 0, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 920, 80));

        TablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaElecciones);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 590, 390));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Día:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Fecha:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Año:");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Mes:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtDia.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bg.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 70, -1));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        bg.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, -1));

        txtMes.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bg.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, -1));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        agregar3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregar3.setText("Agregar");
        agregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar3ActionPerformed(evt);
            }
        });
        bg.add(agregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, -1));

        txtAño.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bg.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setText("Id:");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel18.setText("Tipo:");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Mostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        bg.add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuEleccion abrir = new MenuEleccion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar3ActionPerformed
        int id = TRABAJOEDAGRUPAL.idE;
        String tipo = (String)comboElecciones.getSelectedItem() ;
        if (!txtAño.getText().matches("\\d+") || !txtMes.getText().matches("\\d+") || !txtDia.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Por favor, introduce una fecha válida (solo números).");
        return;
        }

        int año = Integer.parseInt(txtAño.getText());
        int mes = Integer.parseInt(txtMes.getText());
        int dia = Integer.parseInt(txtDia.getText());

        if (tipo == null || tipo.isEmpty()) {
         JOptionPane.showMessageDialog(null, "Por favor, selecciona un tipo de elección.");
        return;
        }

        LocalDate fechaActual = LocalDate.now();

       // Validar que la fecha introducida sea válida
    try {
    LocalDate fechaIngresada = LocalDate.of(año, mes, dia);

       // Validar que la fecha sea del año actual en adelante
       if (fechaIngresada.isBefore(fechaActual)) {
           JOptionPane.showMessageDialog(null, "La fecha debe ser posterior a la fecha actual.");
       return;
        }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Fecha inválida. Por favor, introduzca una fecha válida.");
          return;
        }

        Eleccion eleccion = new Eleccion(id,tipo, dia,mes,año);
        Elecciones.add(eleccion);
        TRABAJOEDAGRUPAL.idE++;
        this.txtId.setText(Integer.toString(TRABAJOEDAGRUPAL.idE));
        

        JOptionPane.showMessageDialog(null, "Eleccion creada correctamente");
        CargarTablaElecciones();


        this.comboElecciones.setSelectedIndex(-1);
        this.txtAño.setText("");
        this.txtMes.setText("");
        this.txtDia.setText("");
    }//GEN-LAST:event_agregar3ActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Datos Actualizados");
        CargarTablaElecciones();
    }//GEN-LAST:event_MostrarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdActionPerformed

    public void CargarTablaElecciones(){
        
        int filas = this.TablaElecciones.getRowCount();
        
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);      
        }
        
        if (Elecciones.getFirst() == null) {
        JOptionPane.showMessageDialog(null, "No hay elecciones para mostrar");
        }

        String[] datos = new String[6];
        for(Eleccion eleccion : Elecciones){
            datos[0] = String.valueOf(eleccion.getId());
            datos[1] = eleccion.getTipo();
            datos[2] = String.valueOf(eleccion.getFecha().getYear());
            datos[3] = String.valueOf(eleccion.getFecha().getMonthValue());
            datos[4] = String.valueOf(eleccion.getFecha().getDayOfMonth());
            datos[5] = eleccion.getEstado();

            modelo.addRow(datos); 
        }   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JTable TablaElecciones;
    private javax.swing.JButton agregar3;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
}
