/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Ejecucion.TRABAJOEDAGRUPAL;
import Modelo.Eleccion;
import Modelo.Mesa.*;
import Modelo.Mesa;
import java.util.LinkedList;
import javax.swing.JComboBox;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import javax.swing.JOptionPane;
/**
 *
 * @author joaqu
 */
public class CrearMiembro extends javax.swing.JFrame {

    /**
     * Creates new form CrearMesa
     */
    public CrearMiembro() {
        initComponents();
    }
    String eleccionid;

    int numeroMesa;
    
    public CrearMiembro(String eleccionid, int numeroMesa) {
        initComponents();
        
        this.numeroMesaactual.setText(String.valueOf(numeroMesa));
        idEleccion.setText(eleccionid);
        this.eleccionid = eleccionid;
        this.numeroMesa = numeroMesa;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DNItxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombretxtField = new javax.swing.JTextField();
        CrearMiembrobtn = new javax.swing.JButton();
        cancelarMiembrobtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idEleccion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ApellidotxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ClavetxtField = new javax.swing.JTextField();
        radiobotonpresidente = new javax.swing.JRadioButton();
        radiobotonsecretario = new javax.swing.JRadioButton();
        radiobotonvocal = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numeroMesaactual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 54, 114));

        jPanel3.setBackground(new java.awt.Color(221, 0, 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 55, 112));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ONPE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Elección");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 20));

        DNItxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DNItxtField.setToolTipText("");
        DNItxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNItxtFieldActionPerformed(evt);
            }
        });
        panel1.add(DNItxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 280, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("DNI:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        NombretxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombretxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NombretxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 280, -1));

        CrearMiembrobtn.setBackground(new java.awt.Color(2, 54, 114));
        CrearMiembrobtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrearMiembrobtn.setForeground(new java.awt.Color(255, 255, 255));
        CrearMiembrobtn.setText("Crear");
        CrearMiembrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearMiembrobtnActionPerformed(evt);
            }
        });
        panel1.add(CrearMiembrobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        cancelarMiembrobtn.setBackground(new java.awt.Color(2, 54, 114));
        cancelarMiembrobtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cancelarMiembrobtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMiembrobtn.setText("Cancelar");
        cancelarMiembrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarMiembrobtnActionPerformed(evt);
            }
        });
        panel1.add(cancelarMiembrobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CREAR MIEMBRO");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        idEleccion.setBackground(new java.awt.Color(0, 0, 0));
        idEleccion.setForeground(new java.awt.Color(0, 0, 0));
        idEleccion.setText("ID:");
        panel1.add(idEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 280, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Apellidos:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        ApellidotxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ApellidotxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidotxtFieldActionPerformed(evt);
            }
        });
        panel1.add(ApellidotxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 280, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Clave:");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        ClavetxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ClavetxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClavetxtFieldActionPerformed(evt);
            }
        });
        panel1.add(ClavetxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 280, -1));

        radiobotonpresidente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radiobotonpresidente);
        radiobotonpresidente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        radiobotonpresidente.setForeground(new java.awt.Color(0, 0, 0));
        radiobotonpresidente.setText("Presidente");
        panel1.add(radiobotonpresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        radiobotonsecretario.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radiobotonsecretario);
        radiobotonsecretario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        radiobotonsecretario.setForeground(new java.awt.Color(0, 0, 0));
        radiobotonsecretario.setText("Secretario");
        panel1.add(radiobotonsecretario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        radiobotonvocal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radiobotonvocal);
        radiobotonvocal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        radiobotonvocal.setForeground(new java.awt.Color(0, 0, 0));
        radiobotonvocal.setText("Vocal");
        panel1.add(radiobotonvocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo:");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Numero Mesa");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        numeroMesaactual.setText("numero");
        panel1.add(numeroMesaactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DNItxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNItxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNItxtFieldActionPerformed

    private void CrearMiembrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearMiembrobtnActionPerformed

        boolean correcto = false;
        
        String dni = this.DNItxtField.getText();
        String nombre = this.NombretxtField.getText();
        String apellido = this.ApellidotxtField.getText();
        
        String tipo = "";
        if(this.radiobotonpresidente.isSelected()){
            tipo = "Presidente";
        }
        else if(this.radiobotonsecretario.isSelected()){
            tipo = "Secretario";
        }
        else if(this.radiobotonvocal.isSelected()){
            tipo = "Vocal";
        }       
        
        String clave = this.ClavetxtField.getText();
        
        for (Eleccion eleccion : TRABAJOEDAGRUPAL.Elecciones) {
            if (Integer.parseInt(this.eleccionid) == eleccion.getId()) {
                if (!dni.isEmpty() && !nombre.isEmpty() && !apellido.isEmpty() && !tipo.isEmpty() && !clave.isEmpty()){
                    TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).crearMiembro(dni, nombre, apellido, tipo, clave);
                    correcto = true;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Complete todos los campos");
                    correcto = false;
                }
            }    
        }

        if (correcto == true) {
//            JOptionPane.showMessageDialog(null, "Miembro creado correctamente");
            MenuMesas menuMesas = new MenuMesas(eleccionid);
            menuMesas.setVisible(true);
            this.setVisible(false);
        }
        else{
           JOptionPane.showMessageDialog(null, "No se pudo crear el miembro");
        }

    }//GEN-LAST:event_CrearMiembrobtnActionPerformed

    private void cancelarMiembrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarMiembrobtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarMiembrobtnActionPerformed

    private void NombretxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtFieldActionPerformed

    private void ApellidotxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidotxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidotxtFieldActionPerformed

    private void ClavetxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClavetxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClavetxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearMiembro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidotxtField;
    private javax.swing.JTextField ClavetxtField;
    private javax.swing.JButton CrearMiembrobtn;
    private javax.swing.JTextField DNItxtField;
    private javax.swing.JTextField NombretxtField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelarMiembrobtn;
    private javax.swing.JLabel idEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel numeroMesaactual;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton radiobotonpresidente;
    private javax.swing.JRadioButton radiobotonsecretario;
    private javax.swing.JRadioButton radiobotonvocal;
    // End of variables declaration//GEN-END:variables
}
