/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Ejecucion.TRABAJOEDAGRUPAL;
import Modelo.Eleccion;
import Modelo.Mesa.*;
import Modelo.Mesa;
import java.util.LinkedList;
import javax.swing.JComboBox;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import Modelo.MiembroMesa;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author joaqu
 */
public class MenuMiembro extends javax.swing.JFrame {

    /**
     * Creates new form MenuMesas
     */

    int xMouse,yMouse;
    String eleccionid;
    int numeroMesa;
    String TipoMiembro;
    public MenuMiembro() {
        initComponents(); 
  
    }
    public MenuMiembro(String eleid, int numeroMesa) {
        initComponents();

        JComboBox<String> comboMiembros = new JComboBox<>();
        comboMiembros.removeAllItems(); 
        this.numeroMesa = numeroMesa;

        this.numeromrsatxt.setText(Integer.toString(numeroMesa));
        String seleccion = eleid;
        Eleccion eleccionSeleccionada = null;

        for (Eleccion eleccion : TRABAJOEDAGRUPAL.Elecciones) {
            if (seleccion.equals(String.valueOf(eleccion.getId()))) {
                eleccionSeleccionada = eleccion;
                break;
            }
        }

        if (eleccionSeleccionada != null) {
            for (Mesa mesa : eleccionSeleccionada.getListaMesas()) {
                if (mesa.getNumero() == numeroMesa) { // Solo miembros de la mesa seleccionada
                    for (MiembroMesa miembro : mesa.getListamiembros()) {
                        comboMiembros.addItem(miembro.getTipo());
                    }
                    break; 
                }
            }
        }

        comboMiembros.setSelectedIndex(-1);

        comboMiembros.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = comboMiembros.getSelectedIndex();
                if (selectedIndex == -1) {
                    System.out.println("No has seleccionado ninguna opción.");
                } else {
                    String seleccion = (String) comboMiembros.getSelectedItem();
                    TipoMiembro = seleccion; 
                    System.out.println("Seleccionaste: " + seleccion);
                }
            }
        });

        jPanel1.add(comboMiembros, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 100, 30));

        idEleccion.setText(eleid);
        eleccionid = eleid;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        ModificarMiembro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CrearMiembro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        EliminarMiembro = new javax.swing.JButton();
        idEleccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeromrsatxt = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 54, 114));

        jPanel3.setBackground(new java.awt.Color(221, 0, 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 55, 112));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ONPE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("MENÚ MIEMBROS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        BtnSalir.setBackground(new java.awt.Color(2, 54, 114));
        BtnSalir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        BtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalirMouseClicked(evt);
            }
        });
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 80, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        ModificarMiembro.setBackground(new java.awt.Color(2, 54, 114));
        ModificarMiembro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarMiembro.setForeground(new java.awt.Color(255, 255, 255));
        ModificarMiembro.setText("Modificar Miembro");
        ModificarMiembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMiembroMouseClicked(evt);
            }
        });
        ModificarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMiembroActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 210, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("N° Mesa");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        CrearMiembro.setBackground(new java.awt.Color(2, 54, 114));
        CrearMiembro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrearMiembro.setForeground(new java.awt.Color(255, 255, 255));
        CrearMiembro.setText("Crear Miembro");
        CrearMiembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMiembroMouseClicked(evt);
            }
        });
        CrearMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearMiembroActionPerformed(evt);
            }
        });
        jPanel1.add(CrearMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 210, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Miembro");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        EliminarMiembro.setBackground(new java.awt.Color(2, 54, 114));
        EliminarMiembro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EliminarMiembro.setForeground(new java.awt.Color(255, 255, 255));
        EliminarMiembro.setText("Eliminar Miembro");
        EliminarMiembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMiembroMouseClicked(evt);
            }
        });
        EliminarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMiembroActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 210, 30));

        idEleccion.setText("ID:");
        jPanel1.add(idEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 262, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Elección");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 65, -1));

        numeromrsatxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        numeromrsatxt.setForeground(new java.awt.Color(0, 0, 0));
        numeromrsatxt.setText(" N°");
        jPanel1.add(numeromrsatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalirMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void ModificarMiembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMiembroMouseClicked
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_ModificarMiembroMouseClicked

    private void ModificarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMiembroActionPerformed
        // TODO add your handling code here:
        ModificarMiembro modificarMiembro = new ModificarMiembro(eleccionid, numeroMesa, TipoMiembro);
        modificarMiembro.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ModificarMiembroActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void CrearMiembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMiembroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearMiembroMouseClicked

    private void CrearMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearMiembroActionPerformed
        // TODO add your handling code here:
        CrearMiembro crearMiembro = new CrearMiembro(eleccionid, numeroMesa);
        crearMiembro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CrearMiembroActionPerformed

    private void EliminarMiembroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMiembroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMiembroMouseClicked

    private void EliminarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMiembroActionPerformed
        // TODO add your handling code here:
        
        TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).eliminarMiembro(TipoMiembro);
        JOptionPane.showMessageDialog(null, "Miembro eliminado");
        
    }//GEN-LAST:event_EliminarMiembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMiembro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton CrearMiembro;
    private javax.swing.JButton EliminarMiembro;
    private javax.swing.JButton ModificarMiembro;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idEleccion;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeromrsatxt;
    // End of variables declaration//GEN-END:variables

}
