/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author User
 */
import Modelo.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Ejecucion.*;
import java.util.LinkedList;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;

public class ModificarCandidato extends javax.swing.JFrame {

    /**
     * Creates new form ModificarCandidato
     */
    int IdC;
    private Eleccion eleccionSeleccionada;
    private String DniAnterior;
    private String txtDni;
    private String txtNuevoNombre;
    private String txtNuevoApellido;
    private String txtNuevoPartido;
    public ModificarCandidato() {
        initComponents();
    }
    public ModificarCandidato(int id,String dni){
        initComponents();
        this.DniAnterior = dni;
        this.IdC=id;
        this.eleccionSeleccionada = TRABAJOEDAGRUPAL.buscarEleccionPorId(IdC);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NuevoDni = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        ModificarEleccionBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NuevoPartido = new javax.swing.JTextField();
        MostrarActual = new javax.swing.JButton();
        Regresaralmenuboton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NuevoNombre = new javax.swing.JTextField();
        NuevoApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Nuevo nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        NuevoDni.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoDniActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));

        Aceptar.setBackground(new java.awt.Color(2, 54, 114));
        Aceptar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        ModificarEleccionBoton.setBackground(new java.awt.Color(2, 54, 114));
        ModificarEleccionBoton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarEleccionBoton.setForeground(new java.awt.Color(255, 255, 255));
        ModificarEleccionBoton.setText("Modificar");
        ModificarEleccionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEleccionBotonActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarEleccionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar Candidato");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 190, 30));

        NuevoPartido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPartidoActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 130, 20));

        MostrarActual.setBackground(new java.awt.Color(2, 54, 114));
        MostrarActual.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MostrarActual.setForeground(new java.awt.Color(255, 255, 255));
        MostrarActual.setText("Mostrar info actual");
        MostrarActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActualActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Regresaralmenuboton2.setBackground(new java.awt.Color(2, 54, 114));
        Regresaralmenuboton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Regresaralmenuboton2.setForeground(new java.awt.Color(255, 255, 255));
        Regresaralmenuboton2.setText("Cancelar");
        Regresaralmenuboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresaralmenuboton2ActionPerformed(evt);
            }
        });
        jPanel1.add(Regresaralmenuboton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Nuevo DNI:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Nuevos apellidos:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Nuevo partido político:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        NuevoNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 130, 20));

        NuevoApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoDniActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        MenuCandidato candit = new MenuCandidato(IdC);
        candit.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void ModificarEleccionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEleccionBotonActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false; // Bandera para confirmar si se encuentra el candidato

if (eleccionSeleccionada.getListaCandidatos() != null) {
    for (Candidato candidato : eleccionSeleccionada.getListaCandidatos()) {
        if (candidato.getDni().equals(DniAnterior)) {
            String nuevoDni1 = NuevoDni.getText().trim();
            String nuevoNombre1 = NuevoNombre.getText().trim();
            String nuevoApellido1 = NuevoApellido.getText().trim();
            String nuevoPartido1 = NuevoPartido.getText().trim();

            // Modificar candidato
            eleccionSeleccionada.modificarCandidato(DniAnterior, nuevoDni1, nuevoNombre1, nuevoApellido1, nuevoPartido1);
            encontrado = true; // Marcamos que el candidato fue encontrado y modificado
            break; // Salimos del bucle porque ya encontramos el candidato
        }
    }

    // Mostrar mensaje dependiendo del resultado
    if (encontrado) {
        JOptionPane.showMessageDialog(null, "Candidato modificado exitosamente.");
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró un candidato con el DNI proporcionado.");
    }
} else {
    JOptionPane.showMessageDialog(null, "La lista de candidatos está vacía o no es válida.");
}
    }//GEN-LAST:event_ModificarEleccionBotonActionPerformed

    private void NuevoPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoPartidoActionPerformed

    private void MostrarActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActualActionPerformed
        // TODO add your handling code here:
        this.NuevoDni.setText(txtDni);
        this.NuevoNombre.setText(txtNuevoNombre);
        this.NuevoApellido.setText(txtNuevoApellido);
        this.NuevoPartido.setText(txtNuevoPartido);

    }//GEN-LAST:event_MostrarActualActionPerformed

    private void Regresaralmenuboton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresaralmenuboton2ActionPerformed
        // TODO add your handling code here:
        MenuCandidato candit = new MenuCandidato(IdC);
        candit.setVisible(true);
        dispose();
    }//GEN-LAST:event_Regresaralmenuboton2ActionPerformed

    private void NuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoNombreActionPerformed

    private void NuevoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton ModificarEleccionBoton;
    private javax.swing.JButton MostrarActual;
    private javax.swing.JTextField NuevoApellido;
    private javax.swing.JTextField NuevoDni;
    private javax.swing.JTextField NuevoNombre;
    private javax.swing.JTextField NuevoPartido;
    private javax.swing.JButton Regresaralmenuboton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
