/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Ejecucion.*;
import java.util.LinkedList;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;

public class ModificarEleccion extends javax.swing.JFrame {
    private String txtIdMod;
    private String txtTipoMod;
    private String txtDiaMod;
    private String txtMesMod;
    private String txtAñoMod;
    private int nuevoId;
    String selec;
    JComboBox<String> comboElecciones;
    
    public ModificarEleccion() {
        initComponents();
    }
    public ModificarEleccion(String id, String tipo, String dia, String mes, String año) {
        initComponents();
        
        this.txtIdMod = id;
        this.txtTipoMod = tipo;
        this.txtDiaMod = dia;
        this.txtMesMod = mes;
        this.txtAñoMod = año;
        String[] opciones = {"", "Presidencial", "Municipal", "Regional"};
        comboElecciones = new JComboBox<>(opciones);

        // Configurar el JComboBox
        comboElecciones.setBounds(70, 160, 170, 30); // Usar AbsoluteConstraints
        comboElecciones.setSelectedIndex(-1); // Inicia vacío
        comboElecciones.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = comboElecciones.getSelectedIndex();
                if (selectedIndex == -1) { // Nada seleccionado aún
                    System.out.println("No has seleccionado ninguna opción.");
                } else {
                    selec = (String) comboElecciones.getSelectedItem();
                    System.out.println("Seleccionaste: " + selec);
                }
            }
        });
        bg.add(comboElecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, 30));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt1NuevoId = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        ModificarEleccionBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NuevoDia = new javax.swing.JTextField();
        MostrarActual = new javax.swing.JButton();
        Regresaralmenuboton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NuevoAño = new javax.swing.JTextField();
        NuevoMes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Nueva Fecha:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        txt1NuevoId.setEditable(false);
        txt1NuevoId.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt1NuevoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1NuevoIdActionPerformed(evt);
            }
        });
        bg.add(txt1NuevoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 20));

        Aceptar.setBackground(new java.awt.Color(2, 54, 114));
        Aceptar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        bg.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        ModificarEleccionBoton.setBackground(new java.awt.Color(2, 54, 114));
        ModificarEleccionBoton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModificarEleccionBoton.setForeground(new java.awt.Color(255, 255, 255));
        ModificarEleccionBoton.setText("Modificar");
        ModificarEleccionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEleccionBotonActionPerformed(evt);
            }
        });
        bg.add(ModificarEleccionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar Eleccion");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Nuevo Día:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        NuevoDia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoDiaActionPerformed(evt);
            }
        });
        bg.add(NuevoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 140, 20));

        MostrarActual.setBackground(new java.awt.Color(2, 54, 114));
        MostrarActual.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MostrarActual.setForeground(new java.awt.Color(255, 255, 255));
        MostrarActual.setText("Mostrar info actual");
        MostrarActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActualActionPerformed(evt);
            }
        });
        bg.add(MostrarActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        Regresaralmenuboton2.setBackground(new java.awt.Color(2, 54, 114));
        Regresaralmenuboton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Regresaralmenuboton2.setForeground(new java.awt.Color(255, 255, 255));
        Regresaralmenuboton2.setText("Cancelar");
        Regresaralmenuboton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresaralmenuboton2ActionPerformed(evt);
            }
        });
        bg.add(Regresaralmenuboton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Nuevo Id:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Nuevo Año:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Nuevo Mes:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        NuevoAño.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoAñoActionPerformed(evt);
            }
        });
        bg.add(NuevoAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, 20));

        NuevoMes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoMesActionPerformed(evt);
            }
        });
        bg.add(NuevoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Nuevo Tipo:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1NuevoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1NuevoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1NuevoIdActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        MenuEleccion menu = new MenuEleccion();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void ModificarEleccionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEleccionBotonActionPerformed
        // TODO add your handling code here:
        if (Elecciones != null) {
            if (!NuevoAño.getText().matches("\\d+") || !NuevoMes.getText().matches("\\d+") || !NuevoDia.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Por favor, introduce una fecha válida (solo números en los campos de año, mes y día).");
            return;
            }
            nuevoId = TRABAJOEDAGRUPAL.idE;
            String nuevoTipoa = (String)comboElecciones.getSelectedItem() ;
            int nuevoAño = Integer.parseInt(NuevoAño.getText());
            int nuevoMes = Integer.parseInt(NuevoMes.getText());
            int nuevoDia = Integer.parseInt(NuevoDia.getText());
            LocalDate fechaActual = LocalDate.now();
            LocalDate fechaIngresada;
            try {
            fechaIngresada = LocalDate.of(nuevoAño, nuevoMes, nuevoDia);

            if (fechaIngresada.isBefore(fechaActual)) {
                JOptionPane.showMessageDialog(null, "La fecha debe ser posterior a la fecha actual.");
                return;
            }
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fecha inválida. Por favor, introduce una fecha válida.");
            return;
            }

            
             
            TRABAJOEDAGRUPAL.modificarEleccion(Integer.parseInt(txtIdMod),nuevoId, nuevoTipoa, LocalDate.of(nuevoAño, nuevoMes, nuevoDia));
            TRABAJOEDAGRUPAL.idE++;
            txt1NuevoId.setText(Integer.toString(nuevoId));
        }
    }//GEN-LAST:event_ModificarEleccionBotonActionPerformed

    private void NuevoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoDiaActionPerformed

    private void MostrarActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActualActionPerformed
        // TODO add your handling code here:
        this.comboElecciones.setSelectedIndex(-1);
        this.NuevoDia.setText(txtDiaMod);
        this.NuevoMes.setText(txtMesMod);
        this.NuevoAño.setText(txtAñoMod);
    }//GEN-LAST:event_MostrarActualActionPerformed

    private void Regresaralmenuboton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresaralmenuboton2ActionPerformed
        // TODO add your handling code here:
        MenuEleccion menu = new MenuEleccion();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_Regresaralmenuboton2ActionPerformed

    private void NuevoAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoAñoActionPerformed

    private void NuevoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton ModificarEleccionBoton;
    private javax.swing.JButton MostrarActual;
    private javax.swing.JTextField NuevoAño;
    private javax.swing.JTextField NuevoDia;
    private javax.swing.JTextField NuevoMes;
    private javax.swing.JButton Regresaralmenuboton2;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1NuevoId;
    // End of variables declaration//GEN-END:variables
}
