/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Ejecucion.TRABAJOEDAGRUPAL;
import Modelo.Eleccion;
import Modelo.Mesa.*;
import Modelo.Mesa;
import java.util.LinkedList;
import javax.swing.JComboBox;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import javax.swing.JOptionPane;
/**
 *
 * @author joaqu
 */
public class ModificarMesa extends javax.swing.JFrame {

    /**
     * Creates new form CrearMesa
     */
    public ModificarMesa() {
        initComponents();
    }
    String eleccionid;
    int numeroMesa;
    public ModificarMesa(int numeroMesa, String eleccionid) {
        initComponents();
        
        this.NumeroMesaActualtxt.setText(Integer.toString(numeroMesa));
        this.NumeroMesaModtxtField.setText(Integer.toString(Eleccion.getNumMesa()));
        String actualubi = TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).getUbicacion();
        this.ActualUbicaciontxtField.setText(actualubi);
        idEleccion.setText(eleccionid);
        this.eleccionid = eleccionid;
        this.numeroMesa = numeroMesa;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumeroMesaModtxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NuevaUbicaciontxtField = new javax.swing.JTextField();
        ModMesabtn = new javax.swing.JButton();
        cancelarModMesabtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idEleccion = new javax.swing.JLabel();
        NumeroMesaActualtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ActualUbicaciontxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 54, 114));

        jPanel3.setBackground(new java.awt.Color(221, 0, 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 55, 112));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ONPE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 330));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Elección");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 30));

        NumeroMesaModtxtField.setEditable(false);
        NumeroMesaModtxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NumeroMesaModtxtField.setToolTipText("");
        NumeroMesaModtxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroMesaModtxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NumeroMesaModtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 280, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ubicacion Nueva:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero Actual :");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        NuevaUbicaciontxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevaUbicaciontxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaUbicaciontxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NuevaUbicaciontxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 280, -1));

        ModMesabtn.setBackground(new java.awt.Color(2, 54, 114));
        ModMesabtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModMesabtn.setForeground(new java.awt.Color(255, 255, 255));
        ModMesabtn.setText("Modificar");
        ModMesabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModMesabtnActionPerformed(evt);
            }
        });
        panel1.add(ModMesabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        cancelarModMesabtn.setBackground(new java.awt.Color(2, 54, 114));
        cancelarModMesabtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cancelarModMesabtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarModMesabtn.setText("Cancelar");
        cancelarModMesabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarModMesabtnActionPerformed(evt);
            }
        });
        panel1.add(cancelarModMesabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("MODIFICAR MESA");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        idEleccion.setBackground(new java.awt.Color(0, 0, 0));
        idEleccion.setForeground(new java.awt.Color(0, 0, 0));
        idEleccion.setText("ID:");
        panel1.add(idEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 280, 30));

        NumeroMesaActualtxt.setEditable(false);
        NumeroMesaActualtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NumeroMesaActualtxt.setToolTipText("");
        NumeroMesaActualtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroMesaActualtxtActionPerformed(evt);
            }
        });
        panel1.add(NumeroMesaActualtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 280, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numero Nuevo:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ubicacion Actual:");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        ActualUbicaciontxtField.setEditable(false);
        ActualUbicaciontxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ActualUbicaciontxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualUbicaciontxtFieldActionPerformed(evt);
            }
        });
        panel1.add(ActualUbicaciontxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroMesaModtxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroMesaModtxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroMesaModtxtFieldActionPerformed

    private void ModMesabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModMesabtnActionPerformed

        boolean correcto = false;
        
        String ubicacion = NuevaUbicaciontxtField.getText();
        for (Eleccion eleccion : TRABAJOEDAGRUPAL.Elecciones) {    
            if (Integer.parseInt(this.eleccionid) == eleccion.getId()) {
           
                if (!ubicacion.isEmpty()) {
                    eleccion.modificarMesa(numeroMesa, ubicacion);
                    correcto = true;

                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese una ubicacion");
                    correcto = false;
                }
            }     
        }                 

        if (correcto == true) {
//            JOptionPane.showMessageDialog(null, "Mesa modificada correctamente");
            MenuMesas menuMesas = new MenuMesas(eleccionid);
            menuMesas.setVisible(true);
            this.setVisible(false);          
        }
        else{
           JOptionPane.showMessageDialog(null, "No se pudo modificar la mesa");
        }

    }//GEN-LAST:event_ModMesabtnActionPerformed

    private void cancelarModMesabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarModMesabtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarModMesabtnActionPerformed

    private void NuevaUbicaciontxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaUbicaciontxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaUbicaciontxtFieldActionPerformed

    private void NumeroMesaActualtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroMesaActualtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroMesaActualtxtActionPerformed

    private void ActualUbicaciontxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualUbicaciontxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualUbicaciontxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActualUbicaciontxtField;
    private javax.swing.JButton ModMesabtn;
    private javax.swing.JTextField NuevaUbicaciontxtField;
    private javax.swing.JTextField NumeroMesaActualtxt;
    private javax.swing.JTextField NumeroMesaModtxtField;
    private javax.swing.JButton cancelarModMesabtn;
    private javax.swing.JLabel idEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
