/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Ejecucion.TRABAJOEDAGRUPAL;
import Modelo.Eleccion;
import Modelo.Mesa.*;
import Modelo.Mesa;
import java.util.LinkedList;
import javax.swing.JComboBox;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import javax.swing.JOptionPane;
/**
 *
 * @author joaqu
 */
public class ModificarMiembro extends javax.swing.JFrame {

    /**
     * Creates new form CrearMesa
     */
    public ModificarMiembro() {
        initComponents();
    }
    
    String eleccionid;
    String tipoMiembro;
    int numeroMesa;
    
    
    public ModificarMiembro(String eleccionid, int numeroMesa, String tipoMiembro) {
        initComponents();
        
        this.NumeroMesaActualtxt.setText(Integer.toString(numeroMesa));
        idEleccion.setText(eleccionid);
        this.eleccionid = eleccionid;
        this.numeroMesa = numeroMesa;
        this.tipoMiembro = tipoMiembro;
        String actualDni = TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).BuscarMiembro(tipoMiembro).getDni();
        String actualNombre = TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).BuscarMiembro(tipoMiembro).getNombre();
        String actualApellido = TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).BuscarMiembro(tipoMiembro).getApellido();
        String actualClave = TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).BuscarMiembro(tipoMiembro).getClave();
        this.DNIactualtxtField.setText(actualDni);
        this.NombreactualtxtField.setText(actualNombre);
        this.ApellidoActualtxtField1.setText(actualApellido);
        this.TipoActual.setText(tipoMiembro);
        this.ClaveActualtxtField.setText(actualClave);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NuevoDNItxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreactualtxtField = new javax.swing.JTextField();
        ModMiembrobtn = new javax.swing.JButton();
        cancelarMiembrobtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idEleccion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NuevoApellidotxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NuevoClavetxtField = new javax.swing.JTextField();
        radiobotonpresidente = new javax.swing.JRadioButton();
        radiobotonsecretario = new javax.swing.JRadioButton();
        radiobotonvocal = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DNIactualtxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NuevoNombretxtField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ApellidoActualtxtField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TipoActual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ClaveActualtxtField = new javax.swing.JTextField();
        NumeroMesaActualtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 54, 114));

        jPanel3.setBackground(new java.awt.Color(221, 0, 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 55, 112));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ONPE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 570));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Elección");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 20));

        NuevoDNItxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoDNItxtField.setToolTipText("");
        NuevoDNItxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoDNItxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NuevoDNItxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 280, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Nombre Actual:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Nuevo DNI:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        NombreactualtxtField.setEditable(false);
        NombreactualtxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NombreactualtxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreactualtxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NombreactualtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 280, 30));

        ModMiembrobtn.setBackground(new java.awt.Color(2, 54, 114));
        ModMiembrobtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ModMiembrobtn.setForeground(new java.awt.Color(255, 255, 255));
        ModMiembrobtn.setText("Modificar");
        ModMiembrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModMiembrobtnActionPerformed(evt);
            }
        });
        panel1.add(ModMiembrobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, 20));

        cancelarMiembrobtn.setBackground(new java.awt.Color(2, 54, 114));
        cancelarMiembrobtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cancelarMiembrobtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelarMiembrobtn.setText("Cancelar");
        cancelarMiembrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarMiembrobtnActionPerformed(evt);
            }
        });
        panel1.add(cancelarMiembrobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("MODIFICAR MIEMBRO");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        idEleccion.setBackground(new java.awt.Color(0, 0, 0));
        idEleccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idEleccion.setText("ID:");
        panel1.add(idEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 280, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Apellidos Nuevo:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 30));

        NuevoApellidotxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoApellidotxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoApellidotxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NuevoApellidotxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 280, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Clave Actual:");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 30));

        NuevoClavetxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoClavetxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoClavetxtFieldActionPerformed(evt);
            }
        });
        panel1.add(NuevoClavetxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 280, 30));

        radiobotonpresidente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radiobotonpresidente);
        radiobotonpresidente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        radiobotonpresidente.setText("Presidente");
        panel1.add(radiobotonpresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, 30));

        radiobotonsecretario.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radiobotonsecretario);
        radiobotonsecretario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        radiobotonsecretario.setText("Secretario");
        panel1.add(radiobotonsecretario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, 30));

        radiobotonvocal.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radiobotonvocal);
        radiobotonvocal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        radiobotonvocal.setText("Vocal");
        panel1.add(radiobotonvocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setText("Tipo:");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, 30));

        jLabel7.setText("Numero Mesa");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        DNIactualtxtField.setEditable(false);
        DNIactualtxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        DNIactualtxtField.setToolTipText("");
        DNIactualtxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIactualtxtFieldActionPerformed(evt);
            }
        });
        panel1.add(DNIactualtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 280, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("DNI Actual:");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("Nuevo Nombre:");
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, 30));

        NuevoNombretxtField1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NuevoNombretxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoNombretxtField1ActionPerformed(evt);
            }
        });
        panel1.add(NuevoNombretxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 280, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setText("Apellido Actual:");
        panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, 30));

        ApellidoActualtxtField1.setEditable(false);
        ApellidoActualtxtField1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ApellidoActualtxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActualtxtField1ActionPerformed(evt);
            }
        });
        panel1.add(ApellidoActualtxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 280, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setText("Tipo:");
        panel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, 30));

        TipoActual.setEditable(false);
        TipoActual.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TipoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActualActionPerformed(evt);
            }
        });
        panel1.add(TipoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 280, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setText("Clave Nueva:");
        panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, 30));

        ClaveActualtxtField.setEditable(false);
        ClaveActualtxtField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ClaveActualtxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveActualtxtFieldActionPerformed(evt);
            }
        });
        panel1.add(ClaveActualtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 280, 30));

        NumeroMesaActualtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NumeroMesaActualtxt.setText("N°mesa:");
        panel1.add(NumeroMesaActualtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 270, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoDNItxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoDNItxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoDNItxtFieldActionPerformed

    private void ModMiembrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModMiembrobtnActionPerformed

        boolean correcto = false;
        
        String dni = this.NuevoDNItxtField.getText();
        String nombre = this.NuevoNombretxtField1.getText();
        String apellido = this.NuevoApellidotxtField.getText();
        
        String tipo = "";
        if(this.radiobotonpresidente.isSelected()){
            tipo = "Presidente";
        }
        else if(this.radiobotonsecretario.isSelected()){
            tipo = "Secretario";
        }
        else if(this.radiobotonvocal.isSelected()){
            tipo = "Vocal";
        }       
        
        String clave = this.NuevoClavetxtField.getText();
        
        for (Eleccion eleccion : TRABAJOEDAGRUPAL.Elecciones) {
            if (Integer.parseInt(this.eleccionid) == eleccion.getId()) {
                if (!dni.isEmpty() && !nombre.isEmpty() && !apellido.isEmpty() && !tipo.isEmpty() && !clave.isEmpty()){
                    TRABAJOEDAGRUPAL.buscarEleccionPorId(Integer.parseInt(eleccionid)).BuscarMesa(numeroMesa).modificarMiembro(tipoMiembro , dni, nombre, apellido, tipo, clave);
                    correcto = true;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Complete todos los campos");
                    correcto = false;
                }
            }    
        }

        if (correcto == true) {
            MenuMesas menuMesas = new MenuMesas(eleccionid);
            menuMesas.setVisible(true);
            this.setVisible(false);
        }
        else{
           JOptionPane.showMessageDialog(null, "No se pudo crear el miembro");
        }

    }//GEN-LAST:event_ModMiembrobtnActionPerformed

    private void cancelarMiembrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarMiembrobtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarMiembrobtnActionPerformed

    private void NombreactualtxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreactualtxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreactualtxtFieldActionPerformed

    private void NuevoApellidotxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoApellidotxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoApellidotxtFieldActionPerformed

    private void NuevoClavetxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoClavetxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoClavetxtFieldActionPerformed

    private void DNIactualtxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIactualtxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNIactualtxtFieldActionPerformed

    private void NuevoNombretxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoNombretxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoNombretxtField1ActionPerformed

    private void ApellidoActualtxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActualtxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActualtxtField1ActionPerformed

    private void TipoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActualActionPerformed

    private void ClaveActualtxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaveActualtxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaveActualtxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMiembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarMiembro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoActualtxtField1;
    private javax.swing.JTextField ClaveActualtxtField;
    private javax.swing.JTextField DNIactualtxtField;
    private javax.swing.JButton ModMiembrobtn;
    private javax.swing.JTextField NombreactualtxtField;
    private javax.swing.JTextField NuevoApellidotxtField;
    private javax.swing.JTextField NuevoClavetxtField;
    private javax.swing.JTextField NuevoDNItxtField;
    private javax.swing.JTextField NuevoNombretxtField1;
    private javax.swing.JLabel NumeroMesaActualtxt;
    private javax.swing.JTextField TipoActual;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelarMiembrobtn;
    private javax.swing.JLabel idEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton radiobotonpresidente;
    private javax.swing.JRadioButton radiobotonsecretario;
    private javax.swing.JRadioButton radiobotonvocal;
    // End of variables declaration//GEN-END:variables
}
