/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Ejecucion.*;
import java.util.LinkedList;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;

public class RegistrarEleccion extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEleccion
     */
    private DefaultTableModel modelo;    
    private RegistrarEleccion refElecciones;
    
    public RegistrarEleccion() {
        initComponents();
        modelo = new DefaultTableModel(); 
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Día");
        modelo.addColumn("Mes");
        modelo.addColumn("Año");

        this.TablaElecciones.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaElecciones = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        agregar1 = new javax.swing.JButton();
        txtDia = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtIdElimin = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        agregar3 = new javax.swing.JButton();
        txtAño = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIdMod = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Eliminar1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(2, 54, 114));
        jLabel15.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 54, 114));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Oficina Nacional de Procesos Electorales");

        jPanel4.setBackground(new java.awt.Color(221, 0, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel16.setBackground(new java.awt.Color(2, 54, 114));
        jLabel16.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 54, 114));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ONPE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel16))
                    .addComponent(jLabel15)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 240, 90));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ELECCION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 60));

        jPanel6.setBackground(new java.awt.Color(2, 54, 114));

        jPanel7.setBackground(new java.awt.Color(221, 0, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 920, 80));

        TablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaElecciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 590, 390));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Día:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Id:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("Fecha:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setText("Año:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("Mes:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        agregar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregar1.setText("Agregar Candidatos");
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 20));

        txtDia.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, -1));

        txtId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 170, -1));

        txtIdElimin.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(txtIdElimin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 110, -1));

        txtMes.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, -1));

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 70, -1));

        Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 20));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Candidatos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 210, -1));

        agregar3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregar3.setText("Agregar");
        agregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar3ActionPerformed(evt);
            }
        });
        jPanel1.add(agregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 20));

        txtAño.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setText("Id:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("Id:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        txtIdMod.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtIdMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdModActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 110, -1));

        Modificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 20));

        Eliminar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 20));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel18.setText("Tipo:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtTipo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        // TODO add your handling code here:
//        RegistroCandidatos regist = new RegistroCandidatos();
//        regist.setVisible(true);

    }//GEN-LAST:event_agregar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Datos Actualizados");
        CargarTablaElecciones();

    }//GEN-LAST:event_ActualizarActionPerformed

    private void agregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar3ActionPerformed
        int id = Integer.parseInt(txtId.getText());
        String tipo = txtTipo.getText();
        int año = Integer.parseInt(txtAño.getText());
        int mes = Integer.parseInt(txtMes.getText());
        int dia = Integer.parseInt(txtDia.getText());

        Eleccion eleccion = new Eleccion(id,tipo, dia,mes,año);
        Elecciones.add(eleccion);

        JOptionPane.showMessageDialog(null, "Eleccion creada correctamente");
        
        this.txtId.setText("");
        this.txtTipo.setText("");
        this.txtAño.setText("");
        this.txtMes.setText("");
        this.txtDia.setText("");

    }//GEN-LAST:event_agregar3ActionPerformed

    private void txtIdModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdModActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:

        String IdMod = this.txtIdMod.getText();
        String tipo = "";
        LocalDate fecha = LocalDate.of(2000, 1, 1);
        for (Eleccion eleccion : Elecciones){
            if (eleccion.getId() == Integer.parseInt(IdMod)) {
                tipo = eleccion.getTipo();
                fecha = eleccion.getFecha();
            }
        }
        if (!IdMod.isEmpty()) {
            for (Eleccion eleccion: Elecciones) {
            ModificarEleccion modificarEleccion = new ModificarEleccion(IdMod,tipo,
                String.valueOf(fecha.getDayOfMonth()),
                String.valueOf(fecha.getMonthValue()),
                String.valueOf(fecha.getYear()));
            modificarEleccion.setVisible(true);
        }
}
        else{
            JOptionPane.showMessageDialog(null, "Ingrese una id de eleccion a modificar");    
        }
        

        this.txtIdMod.setText("");
        this.CargarTablaElecciones();
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:

        String Id = this.txtIdElimin.getText();

        if (!Id.isEmpty()) {
            TRABAJOEDAGRUPAL.eliminarEleccion(Integer.parseInt(Id));
            JOptionPane.showMessageDialog(null, "Eleccion eliminada");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese una id de eleccion a eliminar");
        }

        this.txtIdElimin.setText("");
        CargarTablaElecciones();
    }//GEN-LAST:event_Eliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void CargarTablaElecciones(){
        
        int filas = this.TablaElecciones.getRowCount();
        
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);      
        }
        
        if (Elecciones.getFirst() == null) {
        JOptionPane.showMessageDialog(null, "No hay elecciones para mostrar");
        }

        String[] datos = new String[5];
        for(Eleccion eleccion : Elecciones){
            datos[0] = String.valueOf(eleccion.getId());
            datos[1] = String.valueOf(eleccion.getTipo());
            datos[2] = String.valueOf(eleccion.getFecha().getYear());
            datos[3] = String.valueOf(eleccion.getFecha().getMonthValue());
            datos[4] = String.valueOf(eleccion.getFecha().getDayOfMonth());

            modelo.addRow(datos); 
        }   
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton Modificar;
    private javax.swing.JTable TablaElecciones;
    private javax.swing.JButton agregar1;
    private javax.swing.JButton agregar3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdElimin;
    private javax.swing.JTextField txtIdMod;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
