
package Vista;


import Ejecucion.TRABAJOEDAGRUPAL;
import Modelo.*;
import static Ejecucion.TRABAJOEDAGRUPAL.Elecciones;
import javax.swing.JComboBox;
import java.util.Stack;
import javax.swing.JOptionPane;


public class Votos extends javax.swing.JFrame {

    /**
     * Creates new form Votos
     */
    int idElec;
    int idMesa;
    String candidato;
    String resultado;
    boolean nulo = true;
    public Votos() {
        
        initComponents();
    }
    public Votos(String cantidato, int idElec, int idMesa) {
        this.candidato = cantidato;
        this.idElec = idElec;
        this.idMesa = idMesa;
        initComponents(); //INCIALIZA TODOS LOS COMPONENTES
        for (Candidato candidato : TRABAJOEDAGRUPAL.buscarEleccionPorId(idElec).getListaCandidatos()) {
            if (candidato.getDni().equals(cantidato)) {
                resultado = "Candidato: "+candidato.getNombre() + "\n"+
                            candidato.getApellidos()+ "\n"+
                            "Partido: " + candidato.getPartido();
            }
        }
        this.votofield.setText(resultado);
        this.MostrarMesaLabel.setText(Integer.toString(idMesa));
        this.MostrarEleccionLabel.setText(Integer.toString(idElec));
        
 
    }
    public Votos(int idElec, int idMesa) {
        initComponents(); //INCIALIZA TODOS LOS COMPONENTES
        this.idElec = idElec;
        this.idMesa = idMesa;
        this.MostrarMesaLabel.setText(Integer.toString(idMesa));
        this.MostrarEleccionLabel.setText(Integer.toString(idElec));
    }
    public Votos(boolean nulo, int idElec, int idMesa) {
        this.idElec = idElec;
        this.idMesa = idMesa;
        this.nulo= nulo;
        initComponents(); //INCIALIZA TODOS LOS COMPONENTES
        this.votofield.setText("NULO");
        this.MostrarMesaLabel.setText(Integer.toString(idMesa));
        this.MostrarEleccionLabel.setText(Integer.toString(idElec));
        
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDtextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        VotarButton = new javax.swing.JButton();
        ConfirmarVoto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        votofield = new javax.swing.JTextField();
        MostrarMesaLabel = new javax.swing.JLabel();
        MostrarEleccionLabel = new javax.swing.JLabel();
        RegresarBtn = new javax.swing.JButton();

        IDtextField1.setEditable(false);
        IDtextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(2, 54, 114));

        jPanel4.setBackground(new java.awt.Color(221, 0, 5));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        VotarButton.setBackground(new java.awt.Color(2, 54, 114));
        VotarButton.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        VotarButton.setForeground(new java.awt.Color(255, 255, 255));
        VotarButton.setText("VOTAR");
        VotarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VotarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VotarButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VotarButtonMousePressed(evt);
            }
        });
        VotarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotarButtonActionPerformed(evt);
            }
        });

        ConfirmarVoto.setBackground(new java.awt.Color(2, 54, 114));
        ConfirmarVoto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ConfirmarVoto.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarVoto.setText("Confirmar Voto");
        ConfirmarVoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ConfirmarVoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarVotoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("MESA");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("ELECCION");

        votofield.setEditable(false);
        votofield.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        votofield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        votofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votofieldActionPerformed(evt);
            }
        });

        RegresarBtn.setBackground(new java.awt.Color(2, 54, 114));
        RegresarBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        RegresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegresarBtn.setText("REGRESAR");
        RegresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(votofield, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(RegresarBtn))
                            .addComponent(ConfirmarVoto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostrarMesaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MostrarEleccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(VotarButton)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MostrarEleccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(MostrarMesaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(VotarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(votofield, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmarVoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegresarBtn)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VotarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VotarButtonActionPerformed

    private void VotarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VotarButtonMouseClicked
        // TODO add your handling code here:
        Votar v = new Votar(idElec,idMesa);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VotarButtonMouseClicked

    private void VotarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VotarButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VotarButtonMousePressed

    private void IDtextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtextField1ActionPerformed

    private void ConfirmarVotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarVotoActionPerformed
        // TODO add your handling code here:
        if(!votofield.getText().isEmpty()){
            if (this.nulo) {
            Voto v1= new Voto("valido",candidato);
             
            TRABAJOEDAGRUPAL.buscarEleccionPorId(idElec).BuscarMesa(idMesa).getVotos().add(v1);
            }else{
                Voto v1= new Voto("nulo");

                TRABAJOEDAGRUPAL.buscarEleccionPorId(idElec).BuscarMesa(idMesa).getVotos().add(v1);
            }
            MenuMesas votar = new MenuMesas(Integer.toString(idElec));
            votar.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Voto no válido");
        }
        
        
    
    }//GEN-LAST:event_ConfirmarVotoActionPerformed

    private void votofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votofieldActionPerformed

    private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBtnActionPerformed
        // TODO add your handling code here:
        MenuMesas votar = new MenuMesas(Integer.toString(idElec));
        votar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarVoto;
    private javax.swing.JTextField IDtextField1;
    private javax.swing.JLabel MostrarEleccionLabel;
    private javax.swing.JLabel MostrarMesaLabel;
    private javax.swing.JButton RegresarBtn;
    private javax.swing.JButton VotarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField votofield;
    // End of variables declaration//GEN-END:variables
}
